# fly.toml app configuration file generated for personal-jtfrancis-6494 on 2025-08-17T19:37:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-jtfrancis-6494'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 4242
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
